object BuildVersion {
    object environment {
        private const val majorVersion = 1
        private const val minorVersion = 0
        private const val bugfixVersion = 0

        const val minSdkVersion = 23
        const val compileSdkVersion = 33
        const val targetSdkVersion = 33
        const val applicationId = "io.github.afalalabarce.mvvmproject"
        const val appVersionCode = majorVersion * 1000 + minorVersion * 100 + bugfixVersion
        const val appVersionName = "${majorVersion}.${minorVersion}.$bugfixVersion"
    }

    object jacocoSettings{
        const val jacocoVersion = "0.8.8"
        val codeCoverageExclusions = listOf(
            // data binding
            "android/databinding/**/*.class",
            "**/databinding/*Binding.class",
            "**/android/databinding/*Binding.class",
            "**/android/databinding/*",
            "**/androidx/databinding/*",
            "**/BR.*",
            // android
            "**/R.class",
            "**/R2*.*",
            "**/R2.class",
            "**/R2$*.class",
            "**/R$*.class",
            "**/BuildConfig.*",
            "**/Manifest*.*",
            "**/*Test*.*",
            "android/**/*.*",
            "androidx/**/*.*",
            "com/android/**/*.*",
            "com/google/**/*.*",
            // kotlin
            "**/*MapperImpl*.*",
            "**/*\$ViewInjector*.*",
            "**/*\$ViewBinder*.*",
            "**/*Component*.*",
            "**/*BR*.*",
            "**/*\$Lambda$*.*",
            "**/*Companion*.*",
            "**/*Module*.*",
            "**/*Dagger*.*",
            "**/*Hilt*.*",
            "**/*Koin*.*",
            "**/*MembersInjector*.*",
            "**/*_MembersInjector.class",
            "**/*_Factory*.*",
            "**/*_Provide*Factory*.*",
            "**/*_ViewBinding*.*",
            //"**/*Extensions*.*",
            // sealed and data classes
            "**/*\$Result.*",
            "**/*\$Result$*.*",
            // adapters generated by moshi
            "**/*JsonAdapter.*",
            // others
            "**/AutoValue_*.*",
            "**/*Directions$*",
            "**/*Directions.*",
            "**/*JavascriptBridge.class",
            "**/*\$InjectAdapter.class",
            "**/*\$ModuleAdapter.class",
            "**/*Mock*.*", // Mock classes
        )
    }
}