package io.github.afalalabarce.mvvmproject.model.common

val supportedDateFormat = listOf(
    "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
    "yyyy-MM-dd'T'HH:mm:ss.SSS",
    "yyyy-MM-dd'T'HH:mm:ss",
    "yyyy-MM-dd",
    "dd-MM-yyyy'T'HH:mm:ss.SSS'Z'",
    "dd-MM-yyyy'T'HH:mm:ss.SSS",
    "dd-MM-yyyy'T'HH:mm:ss",
    "dd-MM-yyyy",
    "yyyy/MM/dd'T'HH:mm:ss.SSS'Z'",
    "yyyy/MM/dd'T'HH:mm:ss.SSS",
    "yyyy/MM/dd'T'HH:mm:ss",
    "yyyy/MM/dd",
    "dd/MM/yyyy'T'HH:mm:ss.SSS'Z'",
    "dd/MM/yyyy'T'HH:mm:ss.SSS",
    "dd/MM/yyyy'T'HH:mm:ss",
    "dd/MM/yyyy",
    "yyyy.MM.dd'T'HH:mm:ss.SSS'Z'",
    "yyyy.MM.dd'T'HH:mm:ss.SSS",
    "yyyy.MM.dd'T'HH:mm:ss",
    "yyyy.MM.dd",
    "dd.MM.yyyy'T'HH:mm:ss.SSS'Z'",
    "dd.MM.yyyy'T'HH:mm:ss.SSS",
    "dd.MM.yyyy'T'HH:mm:ss",
    "dd.MM.yyyy",
)